server:
  port: 8081

spring:
  application:
    name: spring-ai-agentic
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_CHAT_MODEL:gpt-4o-mini}
      embedding:
        options:
          model: ${SPRING_AI_OPENAI_EMBEDDING_MODEL:text-embedding-3-small}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

faq:
  source-file: ${FAQ_SOURCE_FILE:/opt/data/mytechstore-faq.md}

chroma:
  url: ${APP_CHROMA_URL:http://chroma-faq:8000}
  collection-prefix: ${APP_CHROMA_COLLECTION_NAME_PREFIX:faq_}
