apiVersion: v1
kind: Service
metadata:
  name: {{ include "langchain-rag-services.fullname" . }}
  labels:
    {{- include "langchain-rag-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceConfig.type }}
  ports:
    - port: {{ .Values.serviceConfig.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "langchain-rag-services.selectorLabels" . | nindent 4 }}
