server:
  port: 8083

spring:
  application:
    name: spring-ai-corrective
  cache:
    type: redis
    redis:
      time-to-live: 400000
      key-prefix: "corrective-rag:"
  data:
    redis:
      host: ${REDIS_HOST:redis-cache}
      port: ${REDIS_PORT:6379}
      timeout: 2000ms
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_CHAT_MODEL:gpt-4o-mini}
      embedding:
        options:
          model: ${SPRING_AI_OPENAI_EMBEDDING_MODEL:text-embedding-3-small}

faq:
  source-file: ${FAQ_SOURCE_FILE:/opt/data/mytechstore-faq.md}

chroma:
  url: ${APP_CHROMA_URL:http://chroma-faq:8000}
  collection-prefix: ${APP_CHROMA_COLLECTION_NAME_PREFIX:faq_}
retrieval:
  top-k: ${APP_RAG_TOP_K_RESULTS:6}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: ${TRACING_SAMPLE_PROBABILITY:1.0}
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://zipkin:9411}/api/v2/spans